{% set name = "en_core_sci_sm" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_sm-0.4.0.tar.gz
  sha256: ce30c9c97a4a6ab1f296d84cf587da6b1e3e867b53c17f2197e8f422de69b899
build:
  noarch: python
  number: 0
  skip: True  # [py<35]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - en_core_sci_sm

about:
  home: https://allenai.github.io/scispacy/
  license: Apache
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'A full spaCy pipeline for biomedical data with a ~100k vocabulary.'
  description: |
    en_core_sci_sm is a full spaCy pipeline for biomedical data with a ~100k vocabulary.
  doc_url: https://allenai.github.io/scispacy/
  dev_url: https://github.com/allenai/scispacy