{% set prefix = "spacy-model-" %}
{% set name = "en_core_sci_sm" %}
{% set version = "0.4.0" %}

package:
  name: {{ prefix|lower }}{{ name|lower }}
  version: {{ version }}

source:
  - url: url: https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v{{ version }}/{{ name }}-{{ version }}.tar.gz
    sha256: ce30c9c97a4a6ab1f296d84cf587da6b1e3e867b53c17f2197e8f422de69b899
  - url: http://www.apache.org/licenses/LICENSE-2.0
    sha256: bf598be48348623cae0c27829884b0e5f9151dde6068fdb657299b489a06e46b
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}
    files:
      - LICENSE
    build:
      noarch: python
      number: 0
      script: {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - setuptools
    test:
      imports:
        - {{ name }}sm
      requires:
        - spacy {{ version.split('.')[0] }}.{{ version.split('.')[1] }}.*
      commands:
        - python -c "__import__('{{ name }}').load()"
        - python -c "__import__('spacy').load('{{ name }}')"

about:
  home: https://allenai.github.io/scispacy/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'A full spaCy pipeline for biomedical data with a ~100k vocabulary.'
  description: |
    en_core_sci_sm is a full spaCy pipeline for biomedical data with a ~100k vocabulary.
  doc_url: https://allenai.github.io/scispacy/
  dev_url: https://github.com/allenai/scispacy
  
extra:
  recipe-maintainers: 
    - alejandrodavilam
